### PR TITLE
Refactored log entry to object and tracev3 file

### PR DESCRIPTION
**Pull request by joachimmetz**
* added more test coverage for tracev3 file
* changes to not catch ImportError, NameError, UnboundLocalError in wide exception catch
* added log entry and changes to use object instead of list

### CODE REVIEW

**Comment by joachimmetz** [comment]
@ydkhatri please ensure to test these changes. The large methods with multiple concerns are very hard to refactor.

**Comment by joachimmetz** [comment]
Seeing this PR had no follow up since 2019, closing it

**Comment by Schramp** [comment]
> > Is it time to move to that code-base?
> 
> for what purpose? dtFormats is currently most my testbed

I had the feeling the dtFormats version of the functionality may be the better version.

**Comment by joachimmetz** [comment]
> I had the feeling the dtFormats version of the functionality may be the better version.

better is very subjective, there will be pros and cons, maybe drop me an email, might be easier to discuss what you're looking for and your plans with https://github.com/Schramp/UnifiedLogReader

Not sure what @ydkhatri his plans are for this project, might be good to align to prevent duplication.

For now the work in dtFormats is to better understand the format and be able to debug format changes.

**Comment by Schramp** [comment]
@ydkhatri seems to be bound to other tasks, for now I just forked and aggregated the open issues and went on. Also on my side its a project with a level of "as time permits, but normally I would take the time to review PR's and accept them on my fork. And if @ydkhatri wants to be more involved he is more then welcome to cherry pick from the fork, merge it in, refactor as he seems fit.

**Comment by joachimmetz** [comment]
> I do not want to start a "ownership" war over it.

Definitely not my goal.

My needs are (1) format documentation (now completed by dtFormats) and (2) a well maintained and tested, reusable Python module I could leverage from Plaso. So happy to help out with an effort that aligns with those goals. Unfortunately earlier efforts to get this project into shape have stalled.

If @ydkhatri does not have the bandwidth and no concerns I would encourage him to be explicit about this.

**Comment by ydkhatri** [comment]
Hi @Schramp and @joachimmetz, apologies for the delayed response. I definitely do not have the bandwidth to carry forward with this, as I am too occupied with other stuff. So feel free to do whatever you'd like with it. I trust you will add functionality and improve it. 

@Schramp , I've invited you as contributer now, so you have full control now. I'm just not going to be able to contribute to it, at least not in the near future.

**Comment by joachimmetz** [comment]
@ydkhatri thanks. @Schramp let me know if you want to sync offline about your plans

**Pull request closed without merging**
